version: "3.8"
services:
  # Service de la BD
  database:
    image: postgres:16.0
    container_name: todo-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-todo_db}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-backend
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-todo_db}
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "3001:3000"
    volumes:
      - ./front:/app/front
      - ./backend:/app
    command: ["npm", "run", "start"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 20s
      timeout: 10s
      retries: 3

# Configuration des volumes
volumes:
  db_data:
    name: todo_db_data