version: "3.8"

services:
  database:
    image: postgres:16
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: todo_db
    ports:
      - "3001:3000"
    volumes:
      - ./front:/app/front
      - ./backend:/app
    command: ["npm", "run", "start"]

volumes:
  db_data: